export const config = {
    RPC_URL: 'https://rpc-galileo-1.andromedaprotocol.io:26657',
    REST_URL: 'https://rpc-galileo-1.andromedaprotocol.io:1317',
    EXPLORER_URL: 'https://www.mintscan.io/juno',
    STAKING_URL: 'https://juno.omniflix.co/stake',
    NETWORK_NAME: 'Andromeda',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'galileo-1',
    CHAIN_NAME: 'Galileo',
    COIN_DENOM: 'ANDR',
    COIN_MINIMAL_DENOM: 'uandr',
    COIN_DECIMALS: 6,
    PREFIX: 'andr',
    COIN_TYPE: 118,
    COINGECKO_ID: 'andr-network',
    DEFAULT_GAS: 200000,
    GAS_PRICE_STEP_LOW: 0.001,
    GAS_PRICE_STEP_AVERAGE: 0.0025,
    GAS_PRICE_STEP_HIGH: 0.004,
    FEATURES: ['stargate', 'cosmwasm', 'no-legacy-stdTx', 'ibc-go'],
};
